# Generated by erl2ex (http://github.com/dazuma/erl2ex)
# From Erlang source: (Unknown source file)
# At: 2018-04-09 16:15:16

defmodule Elixirdo.Typeclass do

  def type({:ok, _a}) do
    Elixirdo.Maybe
  end

  def type(:nothing) do
    Elixirdo.Maybe
  end

  def type(_type) do
    :undefined
  end

  def is_typeclass(:functor) do
    true
  end

  def is_typeclass(:applicative) do
    true
  end

  def is_typeclass(_a) do
    false
  end

  def module(:maybe, :functor) do
    Elixirdo.Maybe
  end

  def module(:maybe, :applicative) do
    Elixirdo.Maybe
  end

  def module(type, typeclass) do
    :erlang.exit({:unregisted_module, {type, typeclass}})
  end
end
